# Spring Development =======================================================================================================

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:// {Test-DataBase-Url} :3306/
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create

  thymeleaf:
    cache: false
