# Spring Local =======================================================================================================

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/~/krule
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  thymeleaf:
    cache: false

app:
  props:
    host:
      url: localhost:8080
